spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PATCH
              - PUT
              - OPTIONS
              - DELETE
      httpclient:
        # 커넥션 타임아웃
        connect-timeout: 1000
        # 응답 타임아웃
        response-timeout: 600000
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:9001 #lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            #- RewritePath=/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,PATCH
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false
                  
        - id: product-service
          uri: http://localhost:9002 #lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            #- RewritePath=/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,PATCH
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false
                  
        - id: order-service
          uri: http://localhost:9003 #lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            #- RewritePath=/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,PATCH
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false
                  
        - id: payment-service
          uri: http://localhost:9004 #lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
          filters:
            #- RewritePath=/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,PATCH
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false
                  
        - id: shipping-service
          uri: http://localhost:9005 #lb://shipping-service
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            #- RewritePath=/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,PATCH
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      healthcheck:
        enabled: true
    registry-fetch-interval-seconds: 5 # 서비스 목록 5초마다 캐싱(default : 30초)
    disable-delta: true # 캐싱할 때 변경된 부분만 업데이트(default : false)
    # 유레카 클라이언트 속성 변경 새로고침 비활성화
    refresh:
      enable: false
