spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: junhoe
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # Kafka 클러스터에 대한 초기 연결에 사용할 호스트:포트
      topic: mileage-save
      group-id: mileage # Consumer는 Consumer Group이 존재하기 때문에, 유일하게 식별 가능한 Consumer Group을 작성합니다.
      auto-offset-reset: earliest # Kafka 서버에 초기 offset이 없거나, 서버에 현재 offset이 더 이상 없는 경우 수행할 작업을 작성합니다.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      healthcheck:
        enabled: true
    registry-fetch-interval-seconds: 5 # 서비스 목록 5초마다 캐싱(default : 30초)
    disable-delta: true # 캐싱할 때 변경된 부분만 업데이트(default : false)
    # 유레카 클라이언트 속성 변경 새로고침 비활성화
    refresh:
      enable: false
